# Generated by Django 4.2.2 on 2024-06-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=7021766927, max_length=12),
            preserve_default=False,
        ),
    ]
